"""NSM Core 0.49 application entrypoint."""
from app import main as core
from app import mikrotik_agent as mikrotik_agent_core
from app.static_assets import static_asset_version
from app.activity_route_precedence import install_activity_route_precedence
from app.activity_worklists import install_activity_worklists
from app.agent_fleet import install_agent_fleet
from app.agent_ui import install_agent_ui
from app.api_keys import install_api_keys
from app.api_operations import install_api_operations
from app.backup_capability_guard import install_backup_capability_guard
from app.backup_core import install_backup_core
from app.backup_policy_bridge import install_backup_policy_bridge
from app.backup_restore_tests import install_backup_restore_tests
from app.backup_scheduler_capability_guard import install_backup_scheduler_capability_guard
from app.backup_scope_guard import install_backup_scope_guard
from app.backup_text_tools import install_backup_text_tools
from app.backup_workspace_capabilities import install_backup_workspace_capabilities
from app.branding_runtime import install_branding_runtime
from app.config_drift import install_config_drift
from app.crud_extension import install_crud
from app.customer_drilldown import install_customer_drilldown
from app.customer_tabs import install_customer_tabs
from app.customer_workspace import install_customer_workspace
from app.dashboard_ui import install_dashboard_ui
from app.demo_ui import install_demo_ui
from app.device_backup_explorer import install_device_backup_explorer
from app.device_csv_import import install_device_csv_import
from app.device_csv_route_precedence import promote_device_csv_import_routes
from app.firmware_activation import install_firmware_activation
from app.firmware_activation_privilege_guard import install_firmware_activation_privilege_guard
from app.firmware_package_staging import install_firmware_package_staging
from app.firmware_upgrade_planner import install_firmware_upgrade_planner
from app.firmware_worklist import install_firmware_worklist
from app.fleet_monitoring import install_fleet_monitoring
from app.integrations_hub import install_integrations_hub
from app.inventory_ui import install_inventory_ui
from app.lifecycle_drilldown import install_lifecycle_drilldown
from app.mikrotik_agent import install_mikrotik_agent
from app.mikrotik_agent_generation import install_mikrotik_agent_generation
from app.mikrotik_agent_status import install_mikrotik_agent_status
from app.mikrotik_agent_update import install_mikrotik_agent_self_update
from app.mikrotik_agent_update_ui import install_mikrotik_agent_update_ui
from app.mikrotik_compatibility import install_mikrotik_compatibility_resolver
from app.mikrotik_job_completion_guard import install_mikrotik_job_completion_guard
from app.mikrotik_modern_early import install_mikrotik_modern_early
from app.mikrotik_legacy import router as mikrotik_legacy_router
from app.mikrotik_legacy_jobs import install_mikrotik_legacy_jobs
from app.mikrotik_routeros6 import install_mikrotik_routeros6
from app.mikrotik_legacy_operations import install_mikrotik_legacy_operations, legacy_upgrade_info
from app.mikrotik_legacy_backup import install_mikrotik_legacy_backup
from app.mikrotik_legacy_snapshot_capability import install_mikrotik_legacy_snapshot_capability
from app.mikrotik_legacy_telemetry import install_mikrotik_legacy_telemetry
from app.mikrotik_backup import install_mikrotik_backup
from app.mikrotik_backup_agent import install_mikrotik_backup_agent
from app.mikrotik_backup_finalization_cleanup import install_mikrotik_backup_finalization_cleanup
from app.mikrotik_snapshot_agent import install_mikrotik_snapshot_agent
from app.mikrotik_snapshot_batch import install_mikrotik_snapshot_batch
from app.mikrotik_diagnostics_agent import install_mikrotik_diagnostics_agent
from app.mikrotik_diagnostic_views import install_mikrotik_diagnostic_views
from app.mikrotik_onboarding import install_mikrotik_onboarding
from app.mikrotik_operational_tools import install_mikrotik_operational_tools
from app.mikrotik_firmware_readiness import install_mikrotik_firmware_readiness
from app.mikrotik_modern_syntax import install_mikrotik_modern_syntax_guard
from app.mikrotik_privilege_profile import install_mikrotik_privilege_profile
from app.mikrotik_workspace import install_mikrotik_workspace
from app.mikrotik_workspace_ux import install_mikrotik_workspace_ux
from app.mikrotik_workspace_ux_precedence import install_mikrotik_workspace_ux_precedence
from app.mikrotik_telemetry import install_mikrotik_telemetry
from app.route_precedence import promote_customer_workspace_routes
from app.routerboot_lifecycle import install_routerboot_lifecycle
from app.mikrotik_device_reboot import install_mikrotik_device_reboot
from app.reports import install_reports
from app.report_schedules import install_report_schedules
from app.search_enhancement import install_search_enhancement
from app.security_drilldown import install_security_drilldown
from app.ui_action_center_feedback import install_ui_action_center_feedback
from app.ui_action_feedback import install_ui_action_feedback
from app.ui_api_key_feedback import install_ui_api_key_feedback
from app.ui_backup_feedback import install_ui_backup_feedback
from app.ui_backup_policy_feedback import install_ui_backup_policy_feedback
from app.ui_backup_policy_form_feedback import install_ui_backup_policy_form_feedback
from app.ui_customer_device_bulk_feedback import install_ui_customer_device_bulk_feedback
from app.ui_customer_site_crud_feedback import install_ui_customer_site_crud_feedback
from app.ui_device_crud_feedback import install_ui_device_crud_feedback
from app.ui_extension import install_ui
from app.ui_feedback import install_ui_feedback
from app.ui_firmware_feedback import install_ui_firmware_feedback
from app.ui_firmware_upgrade_feedback import install_ui_firmware_upgrade_feedback
from app.ui_notification_feedback import install_ui_notification_feedback
from app.uisp_connector import install_uisp_connector
from app.uisp_sync import install_uisp_sync
from app.advisory_admin import install_advisory_admin
from app.vulnerability_remediation import install_vulnerability_remediation
from app.incidents import install_incidents
from app.incident_evidence import install_incident_evidence
from app.compliance import install_compliance
from app.compliance_findings import install_compliance_findings
from app.lifecycle_catalog import install_lifecycle_catalog
from app.lifecycle_remediation import install_lifecycle_remediation
from app.uisp_onboarding import install_uisp_onboarding
from app.routeros_catalog import install_routeros_catalog
from app.firmware_suggestions import install_firmware_suggestions
from app.system_status import install_system_status
from app.api_key_lifecycle import install_api_key_lifecycle
from app.login_security import install_login_security
from app.genieacs_connector import install_genieacs_connector
from app.workflow_ui import install_workflow_ui

APP_VERSION = "0.49.32"
core.APP_VERSION = APP_VERSION
core.app.version = APP_VERSION
core.templates.env.globals["app_version"] = APP_VERSION
core.templates.env.globals["asset_version"] = static_asset_version()
install_ui(core.app, core.templates)
install_ui_feedback(core.app, core.templates)
install_workflow_ui(core.app, core.templates)
install_crud(core.app)
install_api_keys(core.app)
install_api_operations(core.app)
install_device_csv_import(core.app)
install_backup_core(core.app, core.templates)
install_backup_text_tools(core.app)
install_device_backup_explorer(core.app)
install_backup_restore_tests(core.app)
install_backup_scope_guard()
install_backup_capability_guard()
install_backup_policy_bridge()
install_backup_scheduler_capability_guard()
install_demo_ui(core.app)
install_mikrotik_agent(core.app)
install_mikrotik_backup(core.app)
install_mikrotik_backup_agent(core.app)
install_config_drift(core.app)
install_mikrotik_snapshot_agent()
install_mikrotik_diagnostics_agent()
install_mikrotik_diagnostic_views()
install_mikrotik_operational_tools()
install_mikrotik_firmware_readiness(core.app)
install_firmware_package_staging(core.app)
install_firmware_activation(core.app)
install_routerboot_lifecycle(core.app)
install_mikrotik_device_reboot(core.app)
install_firmware_activation_privilege_guard()
install_firmware_upgrade_planner(core.app)
install_agent_ui(core.app)
install_uisp_connector(core.app)
install_uisp_sync(core.app)
install_advisory_admin(core.app)
install_vulnerability_remediation(core.app)
install_incidents(core.app)
install_incident_evidence(core.app)
install_compliance(core.app)
install_compliance_findings(core.app)
install_lifecycle_catalog(core.app)
install_lifecycle_remediation(core.app)
install_uisp_onboarding(core.app)
install_routeros_catalog(core.app)
install_firmware_suggestions(core.app)
install_system_status(core.app)
install_api_key_lifecycle(core.app)
install_login_security(core.app)
install_genieacs_connector(core.app)
install_customer_workspace(core.app)
install_backup_workspace_capabilities(core.app)
promote_customer_workspace_routes(core.app)
install_customer_drilldown(core.app)
install_security_drilldown(core.app)
install_lifecycle_drilldown(core.app)
install_firmware_worklist(core.app)
install_fleet_monitoring(core.app)
install_integrations_hub(core.app)
install_agent_fleet(core.app)
install_customer_tabs(core.app)
install_search_enhancement(core.app)
install_mikrotik_workspace(core.app)
install_mikrotik_workspace_ux(core.app)
install_mikrotik_snapshot_batch(core.app)
install_mikrotik_agent_status(core.app)
install_mikrotik_onboarding(core)
install_mikrotik_telemetry(core.app)
install_dashboard_ui(core.app)
install_inventory_ui(core.app)
install_branding_runtime(core.app)
promote_device_csv_import_routes(core.app)
install_activity_worklists(core.app)
install_reports(core.app)
install_report_schedules(core.app)
privileged_bootstrap = install_mikrotik_privilege_profile()
mikrotik_agent_core._bootstrap_script = privileged_bootstrap
# Legacy telemetry patches the APIRouter before FastAPI copies its routes.
install_mikrotik_legacy_telemetry()
core.app.include_router(mikrotik_legacy_router)
install_mikrotik_legacy_jobs(core.app)
install_mikrotik_legacy_snapshot_capability()
install_mikrotik_backup_finalization_cleanup()
install_mikrotik_compatibility_resolver()
install_mikrotik_routeros6()
install_mikrotik_legacy_operations(core.app)
install_mikrotik_legacy_backup(core.app)
core.templates.env.globals["legacy_upgrade_info"] = legacy_upgrade_info
# Core 0.49 keeps its product version while the independently versioned device
# agent advances to the maintenance generation selected by this policy.
install_mikrotik_agent_generation()
install_mikrotik_agent_self_update(core.app)
# The syntax guard must wrap the final composed modern source, including the
# Core 0.49 self-update/integrity extension. Installing it earlier would leave
# later wrappers able to re-introduce unsafe RouterOS syntax.
install_mikrotik_modern_syntax_guard()
install_mikrotik_modern_early()
install_mikrotik_agent_update_ui(core.templates)
install_activity_route_precedence(core.app)
install_mikrotik_workspace_ux_precedence(core.app)
# Browser-only action wrappers are installed last so they win FastAPI route
# precedence without changing agent/API JSON contracts.
install_ui_action_feedback(core.app)
install_ui_firmware_feedback(core.app)
install_ui_backup_feedback(core.app)
install_ui_backup_policy_feedback(core.app)
install_ui_backup_policy_form_feedback(core.app)
install_ui_firmware_upgrade_feedback(core.app)
install_ui_device_crud_feedback(core.app)
install_ui_customer_site_crud_feedback(core.app)
install_ui_customer_device_bulk_feedback(core.app)
install_ui_api_key_feedback(core.app)
install_ui_action_center_feedback(core.app)
install_ui_notification_feedback(core.app)
# Machine-facing completion idempotency must be installed after every route
# composer/promoter so no later compatibility or UI layer can shadow it.
install_mikrotik_job_completion_guard(core.app)
app = core.app
