"""Self-update of legacy Agents and automatic Agent updates.

Legacy Agents (RouterOS 6.48/6.49 and 7.12) from 0.49.17 can replace their own
script like modern Agents do (``agent_self_update``), so new NSM features reach
routers that are already paired without a new token:

* the job line is ``id|agent_self_update|<end marker>|``; the Agent downloads the
  source generated by NSM for its own device and secret, checks that it ends
  with the marker (no truncated download) and that RouterOS parses it
  (``:parse``), keeps the previous source as ``nsm-agent-heartbeat-prev`` and
  only then replaces its script;
* the new source runs at the next scheduler tick and NSM verifies the update
  from the version reported by the heartbeat;
* a 7.12 router upgraded to 7.13+ receives the modern Agent through the same
  job (transport switch), still keeping the installed RouterOS policies.

RouterOS never lets a script raise its own policies: an Agent installed
read-only (read,test) must be reinstalled once with the admin profile; after
that every update is automatic.  From 0.49.17 the legacy Agent reports the
policies of its script (``X-NSM-Agent-Policy``) so NSM knows which
administrative operations the router really allows.

The worker queues updates by itself (``auto_update``) for online Agents that
can self-update; ``AGENT_AUTO_UPDATE=0`` turns it off.
"""
from __future__ import annotations

import hashlib
import os
import re
import uuid
from datetime import timedelta

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import PlainTextResponse
from sqlalchemy import select

from app import main as core
from app import mikrotik_agent as agent
from app import mikrotik_agent_update as updater
from app import mikrotik_legacy as legacy
from app import mikrotik_legacy_jobs as legacy_jobs
from app.agent_models import DeviceAgentCredential, DeviceJob
from app.db import SessionLocal
from app.models import Device, utcnow

router = APIRouter()
JOB = updater.UPDATE_JOB_TYPE
LEGACY_SELF_UPDATE_MIN = "0.49.17"
# RouterOS limits /tool fetch output=user to 64 KiB.
MAX_LEGACY_SOURCE = 60000
ACTIVE = ("pending", "delivered", "running")
AUTO_BATCH = 50
RETRY_AFTER = timedelta(hours=24)
# Policies needed by the administrative handlers.
OPS_POLICIES = frozenset({"read", "write", "reboot", "test"})
BACKUP_POLICIES = frozenset({"ftp", "policy", "sensitive"})
STATE_LABELS = {
    "idle": "Nessun aggiornamento richiesto",
    "pending": "In coda: l'agent lo riceverà al prossimo heartbeat",
    "installing": "Script scaricato dal router: installazione in corso",
    "awaiting_heartbeat": "Installato: in attesa del primo heartbeat con la nuova versione",
    "verified": "Aggiornamento verificato",
    "failed": "Aggiornamento non riuscito",
    "rolled_back": "Aggiornamento annullato: ripristinato lo script precedente",
    "expired": "Nessun esito entro 30 minuti",
}
_POLICY_SPLIT = re.compile(r"[;,_\s]+")
_MARKER_RE = re.compile(r"^NSM-END-[0-9A-Za-z.-]+$")

_POLICY_PROBE = (
    ':local nsmAgentPolicy ""\n'
    ':do { :set nsmAgentPolicy [:tostr [/system script get [find where name="nsm-agent-heartbeat"] policy]] } on-error={}\n'
)


def _handler(base_url: str, check_certificate: bool) -> str:
    cert = " check-certificate=yes" if check_certificate else ""
    source_url = f'("{base_url}/api/v1/agents/mikrotik/legacy/self-update/" . $nsmJobId . "/source")'
    return f'''            :if ($nsmJobType = "{JOB}") do={{
              :local nsmUpdId [/system script find where name="nsm-agent-heartbeat"]
              :if ([:len $nsmUpdId] != 1) do={{ :error "NSM agent script not found" }}
              :local nsmUpdFetch [/tool fetch url={source_url} http-header-field=$nsmLegacyHeaders output=user as-value{cert}]
              :if (($nsmUpdFetch->"status") != "finished") do={{ :error "NSM agent source download failed" }}
              :local nsmUpdSource ($nsmUpdFetch->"data")
              :local nsmUpdLen [:len $nsmUpdSource]
              :if ($nsmUpdLen < 1000) do={{ :error "NSM agent source too short" }}
              :if ([:typeof [:find [:pick $nsmUpdSource ($nsmUpdLen - 64) $nsmUpdLen] $nsmArg1]] = "nil") do={{ :error "NSM agent source incomplete" }}
              :do {{ :local nsmUpdParsed [:parse $nsmUpdSource] }} on-error={{ :error "NSM agent source rejected by the RouterOS parser" }}
              :local nsmUpdOld [/system script get $nsmUpdId source]
              :local nsmUpdPolicy [/system script get $nsmUpdId policy]
              :do {{ /system script remove [find where name="nsm-agent-heartbeat-prev"] }} on-error={{}}
              :do {{ /system script add name="nsm-agent-heartbeat-prev" policy=$nsmUpdPolicy source=$nsmUpdOld comment="NSM previous agent" }} on-error={{}}
              /system script set $nsmUpdId source=$nsmUpdSource
              :log info ("NSM agent updated: " . $nsmArg1)
              :set nsmJobOutput ("updated=" . $nsmUpdLen . ";marker=" . $nsmArg1)
            }}
'''


def marker(version: str) -> str:
    return f"NSM-END-{version}"


def parse_policies(value) -> list[str]:
    return sorted({part.strip().lower() for part in _POLICY_SPLIT.split(str(value or "")) if part.strip()})


def observed_policies(device) -> set[str] | None:
    value = (device.inventory_data or {}).get("agent_policies")
    return set(value) if isinstance(value, list) else None


def _version(value) -> tuple | None:
    return updater._version_tuple(updater._base_version(value))


def legacy_self_update_capable(device) -> bool:
    data = device.inventory_data or {}
    if str(data.get("agent_transport") or "") != "legacy":
        return False
    current = _version(data.get("agent_version"))
    if not current or current < _version(LEGACY_SELF_UPDATE_MIN):
        return False
    policies = observed_policies(device)
    if policies is not None:
        return "write" in policies
    return str(data.get("agent_privilege_profile") or "") == "legacy-ops-v1"


def transport_upgrade_available(device) -> bool:
    """A legacy Agent on a router that now runs RouterOS 7.13+."""
    data = device.inventory_data or {}
    return str(data.get("agent_transport") or "") == "legacy" and legacy._supports_modern_agent(str(device.firmware_version or ""))


def queue_update(db, device, actor=None, source="portal") -> DeviceJob:
    """Queue an ``agent_self_update`` job (HTTP 409 with the reason when not possible)."""
    credential = db.scalar(select(DeviceAgentCredential).where(
        DeviceAgentCredential.device_id == device.id, DeviceAgentCredential.agent_type == "mikrotik_agent",
        DeviceAgentCredential.is_active.is_(True)))
    if not credential:
        raise HTTPException(409, "Agent non associato.")
    status = updater.agent_update_status(device)
    if not status["self_update_capable"]:
        raise HTTPException(409, status.get("reinstall_reason") or "Questo agent precede l'aggiornamento automatico: reinstallalo una sola volta con un nuovo token.")
    if not status["outdated"]:
        raise HTTPException(409, "Agent già aggiornato e senza drift rilevato.")
    if db.scalar(select(DeviceJob.id).where(DeviceJob.device_id == device.id, DeviceJob.job_type == JOB, DeviceJob.status.in_(ACTIVE))):
        raise HTTPException(409, "Aggiornamento agent già in corso.")
    data = dict(device.inventory_data or {})
    job = DeviceJob(device_id=device.id, job_type=JOB, status="pending", expires_at=utcnow() + updater.UPDATE_JOB_TTL, payload={
        "target_version": updater.TARGET_AGENT_VERSION,
        "transport": data.get("agent_transport"),
        "previous_agent_version": data.get("agent_version"),
        "previous_expected_version": data.get("agent_expected_version"),
        "previous_expected_sha512": data.get("agent_expected_source_sha512"),
        "trigger": source,
    })
    db.add(job)
    db.flush()
    data.update(agent_update_state="pending", agent_update_job_id=str(job.id), agent_update_requested_at=utcnow().isoformat())
    device.inventory_data = data
    core.add_event(db, "MIKROTIK_AGENT_UPDATE_QUEUED", actor=actor, customer_id=device.customer_id, device_id=device.id, source=source,
                   details={"job_id": str(job.id), "target_version": updater.TARGET_AGENT_VERSION, "transport": data.get("agent_transport")})
    return job


def auto_update(now=None) -> dict:
    """Worker tick: update online Agents that can self-update (one attempt per day after a failure)."""
    stats = {"queued": 0}
    if os.getenv("AGENT_AUTO_UPDATE", "1").strip().lower() in {"0", "false", "no", "off"}:
        return stats
    from app.mikrotik_agent_generation import install_mikrotik_agent_generation

    if not getattr(updater.agent_update_status, "_nsm_generation_policy", False):
        install_mikrotik_agent_generation()  # the worker does not import the web entrypoint
    install_status_policy()
    now = now or utcnow()
    with SessionLocal() as db:
        devices = db.scalars(select(Device).join(DeviceAgentCredential, DeviceAgentCredential.device_id == Device.id).where(
            Device.vendor == "mikrotik", Device.status == "online", DeviceAgentCredential.agent_type == "mikrotik_agent",
            DeviceAgentCredential.is_active.is_(True)))
        for device in devices:
            if stats["queued"] >= AUTO_BATCH:
                break
            status = updater.agent_update_status(device)
            if not (status["outdated"] and status["self_update_capable"]):
                continue
            last = db.scalar(select(DeviceJob).where(DeviceJob.device_id == device.id, DeviceJob.job_type == JOB)
                             .order_by(DeviceJob.created_at.desc()).limit(1))
            if last is not None and (last.status in ACTIVE or (last.status == "failed" and (last.completed_at or last.created_at) > now - RETRY_AFTER)):
                continue
            try:
                queue_update(db, device, source="worker")
            except HTTPException:
                continue
            stats["queued"] += 1
        db.commit()
    return stats


def install_status_policy() -> None:
    """Legacy Agents 0.49.17+ with write permission self-update; observed policies decide reinstalls."""
    previous = updater.agent_update_status
    if getattr(previous, "_nsm_legacy_self_update", False):
        return

    def status_with_legacy(device):
        status = previous(device)
        data = device.inventory_data or {}
        policies = observed_policies(device)
        status["policies"] = sorted(policies) if policies is not None else None
        if str(data.get("agent_transport") or "") != "legacy":
            return status
        capable = legacy_self_update_capable(device)
        switch = transport_upgrade_available(device)
        reason = None
        if policies is not None and not OPS_POLICIES <= policies:
            reason = ("Agent installato in sola lettura (permessi RouterOS: " + (", ".join(sorted(policies)) or "nessuno")
                      + "): RouterOS non permette a uno script di aumentarsi i permessi. Reinstallalo una sola volta con un nuovo token; "
                      "dopo, gli aggiornamenti saranno automatici.")
            capable = False
        elif policies is None and not capable:
            reason = status.get("reinstall_reason")
        status["reinstall_reason"] = reason
        status["transport_upgrade"] = switch
        status["self_update_capable"] = capable
        status["outdated"] = bool(status["outdated"] or switch)
        status["requires_reinstall"] = bool(status["outdated"] and not capable)
        status["protocol"] = "legacy-source-v1" if capable else "reinstall-only"
        if switch and capable:
            status["target_version"] = updater.TARGET_AGENT_VERSION
        return status

    status_with_legacy._nsm_legacy_self_update = True
    status_with_legacy._nsm_generation_policy = True  # wraps the generation policy: never wrap it again
    updater.agent_update_status = status_with_legacy
    from app import mikrotik_agent_update_ui as update_ui

    update_ui.agent_update_status = status_with_legacy
    if getattr(core, "templates", None) is not None:
        core.templates.env.globals["mikrotik_agent_update_status"] = status_with_legacy


def _install_source() -> None:
    previous = legacy._legacy_agent_source
    snapshot_marker = '            :if ($nsmJobType = "snapshot_section") do={'
    headers_marker = ':local nsmHeaders ("Content-Type:text/plain,X-NSM-Legacy-Transport:headers-v1,'

    def source(base_url, device_id, raw_secret, check_certificate):
        text = previous(base_url, device_id, raw_secret, check_certificate)
        if snapshot_marker not in text or headers_marker not in text or '",X-NSM-Ifaces:" .' not in text:
            raise RuntimeError("MikroTik legacy self-update extension point not found")
        text = text.replace(headers_marker, _POLICY_PROBE + headers_marker, 1)
        text = text.replace('",X-NSM-Ifaces:" .', '",X-NSM-Agent-Policy:" . [$nsmHeaderSafe $nsmAgentPolicy] . ",X-NSM-Ifaces:" .', 1)
        return text.replace(snapshot_marker, _handler(base_url, check_certificate) + snapshot_marker, 1)

    legacy._legacy_agent_source = source


def _install_job_line() -> None:
    previous = legacy_jobs._job_line

    def job_line(job):
        if job.job_type != JOB:
            return previous(job)
        return f"{job.id}|{JOB}|{marker(updater._target_version_for_transport('legacy'))}|"

    legacy_jobs._job_line = job_line


def _install_inventory() -> None:
    """Record the policies reported by legacy Agents and verify legacy updates and transport switches."""
    previous = agent._apply_inventory
    if getattr(previous, "_nsm_legacy_self_update", False):
        return

    def apply(db, device, inventory, request, source):
        result = previous(db, device, inventory, request, source)
        data = dict(device.inventory_data or {})
        reported = str(inventory.get("agent_version") or "").strip()
        if source == "mikrotik_agent_legacy":
            header = request.headers.get("X-NSM-Agent-Policy") if request is not None else None
            if header:
                policies = parse_policies(header)
                data["agent_policies"] = policies
                data["agent_policies_observed_at"] = utcnow().isoformat()
                profile = "legacy-ops-v1" if OPS_POLICIES <= set(policies) else "legacy-read-v1"
                if data.get("agent_privilege_profile") != profile:
                    core.add_event(db, "MIKROTIK_AGENT_PRIVILEGE_PROFILE_OBSERVED", customer_id=device.customer_id, device_id=device.id,
                                   details={"profile": profile, "policies": policies}, source="mikrotik_agent_legacy")
                data["agent_privilege_profile"] = profile
        elif data.get("agent_transport") == "legacy" and data.get("agent_transport_switch"):
            # First modern heartbeat after a legacy -> modern self-update.
            policies = set(data.get("agent_policies") or [])
            data["agent_transport"] = "modern"
            data["legacy_agent"] = False
            data["agent_privilege_profile"] = "ops-v2" if {"policy", "sensitive", "ftp", "reboot", "write"} <= policies else "ops-v1"
            data.pop("agent_transport_switch", None)
            core.add_event(db, "MIKROTIK_AGENT_TRANSPORT_SWITCHED", customer_id=device.customer_id, device_id=device.id,
                           details={"from": "legacy", "to": "modern", "agent_version": reported, "routeros": device.firmware_version}, source="mikrotik_agent")
        expected = str(data.get("agent_expected_version") or "")
        if (source == "mikrotik_agent_legacy" and data.get("agent_update_state") in {"installing", "awaiting_heartbeat", "expired"}
                and expected and reported == expected):
            data["agent_update_state"] = "verified"
            data["agent_update_verified_at"] = utcnow().isoformat()
            core.add_event(db, "MIKROTIK_AGENT_UPDATE_VERIFIED", customer_id=device.customer_id, device_id=device.id,
                           details={"agent_version": reported, "transport": "legacy"}, source="mikrotik_agent_legacy")
        device.inventory_data = data
        return result

    apply._nsm_legacy_self_update = True
    agent._apply_inventory = apply


def _install_completion() -> None:
    previous = legacy_jobs.legacy_job_complete

    async def complete(request: Request, job_id: uuid.UUID, status: str = "failed"):
        with SessionLocal() as db:
            job = db.get(DeviceJob, job_id)
            job_type = job.job_type if job else None
        if job_type != JOB:
            return await previous(request, job_id, status)
        raw = (await request.body()).decode("utf-8", errors="replace")[:4000]
        with SessionLocal() as db:
            device, _ = agent._authenticate_agent(db, request)
            job = db.get(DeviceJob, job_id)
            if not job or job.device_id != device.id:
                raise HTTPException(404, "Job legacy non trovato.")
            data = dict(device.inventory_data or {})
            ok = str(status).strip().lower() == "success" and raw.startswith("updated=")
            if ok:
                job.status, job.last_error = "success", None
                if data.get("agent_update_state") != "verified":
                    data["agent_update_state"] = "awaiting_heartbeat"
            else:
                job.status = "failed"
                job.last_error = (raw if raw and not raw.startswith("updated=") else
                                  "L'agent non ha installato l'aggiornamento: lo script precedente resta attivo.")
                data["agent_update_state"] = "failed"
                for key, saved in (("agent_expected_version", "previous_expected_version"), ("agent_expected_source_sha512", "previous_expected_sha512")):
                    if (job.payload or {}).get(saved):
                        data[key] = job.payload[saved]
                data.pop("agent_transport_switch", None)
            job.completed_at = utcnow()
            job.result = {**(job.result or {}), "output": raw[:500], "legacy_transport": True}
            device.inventory_data = data
            core.add_event(db, "MIKROTIK_AGENT_UPDATE_COMPLETED", customer_id=device.customer_id, device_id=device.id,
                           severity="warning" if job.status == "failed" else "info", result=job.status, source="mikrotik_agent_legacy",
                           details={"job_id": str(job.id), "state": data["agent_update_state"], "transport": "legacy"})
            db.commit()
        return {"status": "ok"}

    legacy_jobs.legacy_job_complete = complete


@router.get("/api/v1/agents/mikrotik/legacy/self-update/{job_id}/source", response_class=PlainTextResponse, name="mikrotik_legacy_agent_update_source")
def legacy_update_source(request: Request, job_id: uuid.UUID):
    with SessionLocal() as db:
        device, _ = agent._authenticate_agent(db, request)
        job = db.get(DeviceJob, job_id)
        if not job or job.device_id != device.id or job.job_type != JOB:
            raise HTTPException(404, "Job self-update non trovato.")
        if job.status != "delivered":
            raise HTTPException(409, "Job self-update non consegnato.")
        data = dict(device.inventory_data or {})
        if str(data.get("agent_transport") or "") != "legacy":
            raise HTTPException(409, "Self-update legacy non applicabile a questo agent.")
        raw_secret = request.headers.get("X-NSM-Device-Secret", "").strip()
        base_url = str(request.base_url).rstrip("/")
        routeros = str(device.firmware_version or "").split(" ")[0]
        source, transport, version = legacy._select_agent_source(base_url, device.id, raw_secret, routeros)
        end = marker(updater._target_version_for_transport("legacy"))
        source = source.rstrip("\n") + f"\n# {end}\n"
        if len(source.encode("utf-8")) > MAX_LEGACY_SOURCE:
            job.status, job.last_error, job.completed_at = "failed", "Script agent oltre il limite di download di RouterOS (64 KB).", utcnow()
            db.commit()
            raise HTTPException(409, job.last_error)
        digest = hashlib.sha512(source.encode("utf-8")).hexdigest()
        data.update(agent_expected_version=version, agent_expected_source_sha512=digest, agent_update_state="installing",
                    agent_update_delivered_at=utcnow().isoformat(),
                    agent_update_protocol="source-v1" if transport == "modern" else "legacy-source-v1")
        if transport == "modern":
            data["agent_transport_switch"] = "modern"
        device.inventory_data = data
        job.status = "running"
        job.result = {**(job.result or {}), "target_version": version, "transport": transport, "source_sha512": digest, "bytes": len(source)}
        db.commit()
    return PlainTextResponse(source, media_type="text/plain; charset=utf-8", headers={"Cache-Control": "no-store", "X-NSM-Agent-Transport": transport})


def install_mikrotik_agent_autoupdate(app) -> None:
    legacy_jobs.LEGACY_JOB_TYPES = set(legacy_jobs.LEGACY_JOB_TYPES) | {JOB}
    _install_source()
    _install_job_line()
    _install_inventory()
    _install_completion()
    install_status_policy()
    app.include_router(router)
