"""Vulnerability newsletter, scheduled report delivery and worker error alerts.

* Newsletter: each user chooses off / daily / weekly in the profile; when due,
  the worker sends the vulnerabilities newly detected on the inventory in the
  period, with the number of exposed devices per CVE and the open totals, to
  the user's enabled channels.  Nothing is sent when there is nothing new.
* Reports: every report generated by a schedule is queued for the users who
  selected the *Report* category (explicitly, or all categories at the level
  *Informativo*); e-mail carries the file as attachment, other channels a link.
* Worker errors: a periodic task failing three times in a row raises a *high*
  notification (fanned out like any other), and its recovery an informative one.
"""
from __future__ import annotations

from datetime import timedelta

from fastapi import Request
from fastapi.responses import RedirectResponse
from sqlalchemy import event, func, select
from sqlalchemy.orm import Session

from app import main as core
from app import notification_delivery as nd
from app.db import SessionLocal
from app.models import Device, DeviceVulnerability, Notification, SecurityAdvisory, User, utcnow
from app.notification_models import NotificationDelivery, UserNotificationPreference
from app.report_models import GeneratedReport
from app.security import validate_csrf

DIGEST_PERIODS = {"daily": timedelta(days=1), "weekly": timedelta(days=7)}
DIGEST_LABELS = {"off": "Disattivata", "daily": "Giornaliera", "weekly": "Settimanale"}
MAX_ATTACHMENT = 15 * 1024 * 1024
TOP_CVES = 15
WORKER_ALERT_AFTER = 3
SEVERITY_ORDER = {"critical": 3, "high": 2, "medium": 1, "low": 0}


# --- Vulnerability newsletter --------------------------------------------------------------------

def digest_content(db, since, now) -> dict | None:
    rows = db.execute(
        select(SecurityAdvisory.cve_id, SecurityAdvisory.severity, SecurityAdvisory.cvss, SecurityAdvisory.summary,
               func.count(func.distinct(DeviceVulnerability.device_id)))
        .join(DeviceVulnerability, DeviceVulnerability.advisory_id == SecurityAdvisory.id)
        .where(DeviceVulnerability.status != "resolved", DeviceVulnerability.detected_at > since, DeviceVulnerability.detected_at <= now)
        .group_by(SecurityAdvisory.cve_id, SecurityAdvisory.severity, SecurityAdvisory.cvss, SecurityAdvisory.summary)).all()
    if not rows:
        return None
    rows = sorted(rows, key=lambda r: (-SEVERITY_ORDER.get(str(r[1]).lower(), -1), -(r[2] or 0), -r[4]))
    open_findings = db.scalar(select(func.count(DeviceVulnerability.id)).where(DeviceVulnerability.status != "resolved")) or 0
    open_devices = db.scalar(select(func.count(func.distinct(DeviceVulnerability.device_id))).where(DeviceVulnerability.status != "resolved")) or 0
    total_devices = db.scalar(select(func.count(Device.id))) or 0
    new_devices = len({d for (d,) in db.execute(select(DeviceVulnerability.device_id).where(
        DeviceVulnerability.status != "resolved", DeviceVulnerability.detected_at > since, DeviceVulnerability.detected_at <= now))})
    worst = max((SEVERITY_ORDER.get(str(r[1]).lower(), 0) for r in rows), default=0)
    lines = [f"Nuove vulnerabilità rilevate sui tuoi apparati dal {since.astimezone().strftime('%d/%m/%Y %H:%M')}:", ""]
    for cve, severity, cvss, summary, devices in rows[:TOP_CVES]:
        score = f", CVSS {cvss:g}" if cvss is not None else ""
        lines.append(f"• {cve} ({str(severity or 'n.d.').lower()}{score}) — {devices} {'apparato esposto' if devices == 1 else 'apparati esposti'}")
        if summary:
            lines.append(f"  {str(summary)[:160]}")
    if len(rows) > TOP_CVES:
        lines.append(f"… e altre {len(rows) - TOP_CVES} CVE.")
    lines += ["", f"Totale aperto: {open_findings} esposizioni su {open_devices} di {total_devices} apparati."]
    return {"title": f"Newsletter vulnerabilità: {len(rows)} nuove CVE, {new_devices} {'apparato coinvolto' if new_devices == 1 else 'apparati coinvolti'}",
            "body": "\n".join(lines), "level": {3: "critical", 2: "high", 1: "warning"}.get(worst, "info")}


def run_vulnerability_digest(now=None) -> dict:
    now = now or utcnow()
    stats = {"sent": 0, "skipped": 0}
    with SessionLocal() as db:
        for user in db.scalars(select(User).where(User.is_active.is_(True), User.notify_digest.in_(tuple(DIGEST_PERIODS)))):
            period = DIGEST_PERIODS[user.notify_digest]
            last = user.notify_digest_last_at
            if last and now - last < period:
                continue
            content = digest_content(db, last or now - period, now)
            user.notify_digest_last_at = now
            if not content:
                stats["skipped"] += 1
                continue
            queued = nd.queue_direct(db, user, content["title"], content["body"], level=content["level"], category="security",
                                     source_url="/security/vulnerabilities")
            stats["sent" if queued else "skipped"] += 1
        db.commit()
    return stats


async def save_digest(request: Request):
    form = await request.form()
    validate_csrf(request, str(form.get("csrf") or ""))
    with SessionLocal() as db:
        user = core.current_user(request, db)
        if not user:
            return core.login_redirect()
        value = str(form.get("digest") or "off")
        user.notify_digest = value if value in DIGEST_LABELS else "off"
        if user.notify_digest == "off":
            user.notify_digest_last_at = None
        core.add_event(db, "USER_DIGEST_CHANGED", actor=user, details={"digest": user.notify_digest}, source="portal")
        db.commit()
    return RedirectResponse("/profile?status=digest_saved#notifications", status_code=303)


# --- Scheduled report delivery -------------------------------------------------------------------

def _wants_report(pref: UserNotificationPreference) -> bool:
    if not pref.enabled:
        return False
    if "reports" in (pref.categories or []):
        return True
    return not pref.categories and nd.normalize_level(pref.min_severity) == "info"


def queue_report(db, report: GeneratedReport) -> int:
    rows = db.execute(select(UserNotificationPreference, User).join(User, User.id == UserNotificationPreference.user_id)
                      .where(UserNotificationPreference.enabled.is_(True), User.is_active.is_(True))).all()
    title = f"Report pianificato: {report.title}"
    message = f"{report.scope_label} · periodo {report.period_start.strftime('%d/%m/%Y')} – {report.period_end.strftime('%d/%m/%Y')} · {report.output_format.upper()}"
    queued = 0
    for pref, user in rows:
        if pref.channel not in nd.CHANNELS or not _wants_report(pref):
            continue
        destination = nd._destination(pref, user)
        if not destination:
            continue
        subject, body = nd.compose(db, title, message, "info", "reports", f"/audit/reports/{report.id}/download")
        db.add(NotificationDelivery(user_id=user.id, channel=pref.channel, destination=destination, category="reports", severity="info",
                                    subject=subject, body=body, status="pending", next_attempt_at=utcnow(),
                                    attachment_ref=f"report:{report.id}" if pref.channel == "email" else None))
        queued += 1
    return queued


@event.listens_for(Session, "before_flush")
def _queue_new_scheduled_reports(session, flush_context, instances):
    reports = [obj for obj in session.new if isinstance(obj, GeneratedReport) and getattr(obj, "schedule_id", None)]
    if not reports:
        return
    import uuid as _uuid

    with session.no_autoflush:
        for report in reports:
            if report.id is None:
                report.id = _uuid.uuid4()
            queue_report(session, report)


def report_attachment(db, delivery: NotificationDelivery):
    """(filename, media type, bytes) for an e-mail delivery that carries a report, or None."""
    ref = delivery.attachment_ref or ""
    if not ref.startswith("report:"):
        return None
    import uuid as _uuid

    try:
        report = db.get(GeneratedReport, _uuid.UUID(ref.split(":", 1)[1]))
    except ValueError:
        return None
    if not report or report.size_bytes > MAX_ATTACHMENT:
        return None
    return report.filename, report.media_type, bytes(report.content)


# --- Worker error alerts -------------------------------------------------------------------------

def worker_task_alert(name: str, failures: int, error: str | None, recovered: bool = False) -> None:
    """Raise a notification at the third consecutive failure of a worker task, and when it recovers."""
    with SessionLocal() as db:
        if recovered:
            db.add(Notification(severity="info", category="system", title=f"Task del worker ripristinato: {name}",
                                message="Il task è tornato a funzionare.", source_url="/admin/system"))
        else:
            db.add(Notification(severity="high", category="system", title=f"Task del worker in errore: {name}",
                                message=f"{failures} errori consecutivi. Ultimo errore: {error or 'sconosciuto'}", source_url="/admin/system"))
        db.commit()


def install_notification_digest(app) -> None:
    app.add_api_route("/profile/notifications/digest", save_digest, methods=["POST"], name="profile_notifications_digest", include_in_schema=False)
    core.templates.env.globals["digest_labels"] = DIGEST_LABELS
