"""Hardened entry point of the syslog receiver container (LOG-01 hardening).

Runs before anything imports the database settings:

- with ``SYSLOG_DB_PASSWORD`` (generated by ``update.sh`` in
  ``secrets/bootstrap.env``) the receiver connects as the dedicated role
  ``nsm_syslog`` (see ``app.db_roles``), which can only insert log lines and
  read devices and the syslog settings;
- secrets the receiver never needs are removed from its environment, so a
  compromise of this internet-facing process does not expose them.
"""
from __future__ import annotations

import logging
import os

ROLE = "nsm_syslog"
NOT_NEEDED = ("APP_SECRET_KEY", "ENCRYPTION_MASTER_KEY", "ENCRYPTION_PREVIOUS_KEYS", "GENIEACS_UI_JWT_SECRET")


def prepare_environment(environ=os.environ) -> bool:
    """Switch to the dedicated database role when configured; True when it is used."""
    dedicated = bool(environ.get("SYSLOG_DB_PASSWORD"))
    if dedicated:
        environ["DB_USER"] = ROLE
        environ["POSTGRES_PASSWORD"] = environ["SYSLOG_DB_PASSWORD"]
    for name in NOT_NEEDED:
        environ.pop(name, None)
    environ["SYSLOG_DEDICATED_DB"] = "1" if dedicated else "0"
    return dedicated


def main() -> None:
    dedicated = prepare_environment()
    from app import syslog_receiver

    if not dedicated:
        logging.getLogger("nsm.syslog").warning("SYSLOG_DB_PASSWORD not set: the receiver uses the main database account (run update.sh)")
    syslog_receiver.main()


if __name__ == "__main__":
    main()
