"""Initial core schema."""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("username", sa.String(100), nullable=False), sa.Column("password_hash", sa.String(512), nullable=False), sa.Column("role", sa.String(30), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("username"))
    op.create_table("customers", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("code", sa.String(80), nullable=True), sa.Column("notes", sa.Text(), nullable=True), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("code"))
    op.create_table("sites", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("customer_id", sa.Uuid(), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("address", sa.String(300), nullable=True), sa.Column("notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["customer_id"],["customers.id"],ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_sites_customer_id", "sites", ["customer_id"])
    op.create_table("devices", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("customer_id", sa.Uuid(), nullable=False), sa.Column("site_id", sa.Uuid(), nullable=True), sa.Column("vendor", sa.String(60), nullable=False), sa.Column("family", sa.String(100), nullable=True), sa.Column("device_type", sa.String(60), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("model", sa.String(150), nullable=True), sa.Column("serial_number", sa.String(150), nullable=True), sa.Column("primary_mac", sa.String(17), nullable=True), sa.Column("management_ip", sa.String(255), nullable=True), sa.Column("firmware_version", sa.String(150), nullable=True), sa.Column("management_source", sa.String(60), nullable=False), sa.Column("external_device_id", sa.String(255), nullable=True), sa.Column("status", sa.String(30), nullable=False), sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["customer_id"],["customers.id"],ondelete="CASCADE"), sa.ForeignKeyConstraint(["site_id"],["sites.id"],ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("vendor","primary_mac",name="uq_devices_vendor_primary_mac"))
    for name, cols in [("ix_devices_customer_id",["customer_id"]),("ix_devices_site_id",["site_id"]),("ix_devices_vendor",["vendor"]),("ix_devices_status",["status"])]: op.create_index(name,"devices",cols)
    op.create_table("audit_events", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("customer_id", sa.Uuid(), nullable=True), sa.Column("device_id", sa.Uuid(), nullable=True), sa.Column("actor_user_id", sa.Uuid(), nullable=True), sa.Column("source", sa.String(50), nullable=False), sa.Column("result", sa.String(30), nullable=False), sa.Column("details", sa.JSON(), nullable=False), sa.ForeignKeyConstraint(["actor_user_id"],["users.id"],ondelete="SET NULL"), sa.ForeignKeyConstraint(["customer_id"],["customers.id"],ondelete="SET NULL"), sa.ForeignKeyConstraint(["device_id"],["devices.id"],ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    for name, cols in [("ix_audit_events_timestamp",["timestamp"]),("ix_audit_events_event_type",["event_type"]),("ix_audit_events_customer_id",["customer_id"]),("ix_audit_events_device_id",["device_id"])]: op.create_index(name,"audit_events",cols)

def downgrade():
    op.drop_table("audit_events"); op.drop_table("devices"); op.drop_table("sites"); op.drop_table("customers"); op.drop_table("users")
